# Generated by Django 3.2 on 2021-05-04 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myPlaceRemember', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='remembermodel',
            name='slug',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
